title: Mr.Q's HUB
email: mikustokes@gmail.com
description: 
base_url: "http://mrq02.github.io"
url: "http://mrq02.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: QuStokes
github_username:  mrq02

# Build settings
theme: minima
plugins:
  - jekyll-feed

nav:
    - {title: Main, description: Back to Main, url: '/'}
    - {title: CV, description: My CV, url: '/CV/'}
    - {title: Roadmap, description: Roadmap of notes, url: '/roadmap/'}
    - {title: Projects, description: My Projects, url: 'http://github.com/mrq02'}
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
